# To create basic 2 layer and 3 layer neural networks and train them using Gradient Descent

In [457]:
from numpy import exp, array, random, dot

In [456]:
import pandas as pd
import numpy as np
from __future__ import print_function

In [458]:
# define a sigmoid function 
def sigmoid(x):
    return 1/(1 + exp(-x))

In [469]:
# theta here is the vector of parameters for the features . The parameters have to randomly initialized or else all the 
# parameters will update to the same value inn ecah iteration of back propagation.

theta = 2*3*random.random((2,1)) -3
theta

array([[ 2.43235391],
       [-0.24071841]])

# First to create a 2 layer network with 2 input nodes and one output node

In [460]:
# now we are going to write a function to train the neural network. We do this by gradient descent
# Formulae used:
# output vector = a_2 = sigmoid(x*theta)
# the derivative of the cost is to be subtracted from the paramter vector and = (h(x) - y).x_i = (a_2 - y).x_i
# keep doing this till the paarmeters converge to the global minimum

def train(x,y,n_iter,theta):
    for i in np.arange(n_iter):
        y_pred = sigmoid(dot(x,theta))
        o = y_pred - y
        s = theta - dot(x.T,o*((y_pred)*(1 - (y_pred))))
    return s
    

In [461]:
# these are the training values

training_set_inputs = array([[1,0,], [0,1], [0,0]])
training_set_outputs = array([[1,1,0]]).T

In [470]:
theta = train(training_set_inputs,training_set_outputs,10000,theta)

In [471]:
theta

array([[ 2.43834632],
       [-0.102754  ]])

In [472]:
# predicting the value for a new set of inputs using the trained network
dot([1,1],theta)

array([ 2.33559232])

# Now for a 3 layer network with 3 in put nodes, 4 nodes in the hidden layer and one output node

In [473]:
# This time we have 2 parameter matrices. One for the first layer and the other for the hidden layer.
# theta_1 = matrix for layer 1 
# theta_2 = matrix for layer 2
# They have to be randomly initialized or else in each iteration they will be update dto the same value

theta_1 = 2*random.random((3,4)) - 1

In [474]:
theta_1 

array([[ 0.09269363,  0.59720718, -0.4285623 , -0.01949295],
       [ 0.19822062, -0.96893345,  0.18696282, -0.1326473 ],
       [ 0.61472106, -0.36951039,  0.78577742,  0.15571443]])

In [475]:
theta_2 = 2*random.random((4,1))  - 1

In [476]:
# these are the training values

x_inp = array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1], [0, 0, 0]])
y_inp = array([[0, 1, 1, 1, 1, 0, 0]]).T

In [479]:
# now we are going to write a function to train the neural network. We do this by gradient descent
# Formulae used:
# hidden layer = a_2 = sigmoid(x*theta_1)
# output layer = a_3 = sigmoid(a_2*theta_2)
# the derivative of the cost is to be subtracted from the paramter vector 
# We have to this by BACK PROPAGATION
# the gradient can be found with the matrix DELTA 
# the elements of this matrix are delta_2 and delta_3
# delta_3 = a_3 - y
# delta_2 = (delta_3*tarnspose(theta_2))*((derivative of sigmoid of (z_2))) = (delta_3*tarnspose(theta_2))*(a_2)(1 - a_2)
# we finally have to subtract the following values from the parameter matrices
# 1. (transpose(a_2)*delta_3)
# 2. (transpose(x)*delta_2)
# keep doing this till the paarmeters converge to the global minimum


def train_2(x,y,n,theta_1,theta_2):
    for i in np.arange(n):
        a_2 = sigmoid(dot(x,theta_1))
        a_3 = sigmoid(dot(a_2,theta_2))
        delta_3 = a_3 - y
        delta_2 = dot(delta_3,theta_2.T)*(a_2*(1-a_2))
        adj_2 = dot(a_2.T,delta_3) 
        adj_1 = dot(x.T,delta_2)
        theta_1 = theta_1 - adj_1
        theta_2 = theta_2 - adj_2
           
    return theta_1,theta_2

In [480]:
theta_1,theta_2 = train_2(x_inp,y_inp,1000,theta_1,theta_2)

In [481]:
# here we predict the value for a new datum with the trained network 

b_1 = dot(array([1,1,0]),theta_1)
outp = dot(b_1,theta_2)

In [482]:
outp

array([ 200.49191412])

Now just define a threshhold for deciding when it is 1 and when it is 0

In [446]:
theta_1

array([[  2.20463624,   1.96471215,   1.75361684,   0.71336645],
       [  1.13858924,   1.3885062 ,   1.80524925,   2.63459102],
       [ 14.07208213,  14.07288205,  14.06511942,  14.07295151]])

In [447]:
theta_2

array([[ 2493.77938279],
       [ 2495.27127824],
       [ 2494.60507123],
       [ 2495.09873652]])